# Course part 3 done on IntelliJ IDEA Ultimate, API tested using IDE's HTTP Client Tool

### View root api route
# 200: Returns <h1>Hello World!</h1>
GET http://localhost:3001/api

### Get all notes
# 200: List of all notes
GET http://localhost:3001/api/notes

### Get single note with ID:65162ace54bf62553acae768
# 200: JSON of single note with note.id=65162ace54bf62553acae768
GET http://localhost:3001/api/notes/65162ace54bf62553acae768

### Get non-existent note with ID:65162ace54bf62553acae767
# 404
GET http://localhost:3001/api/notes/65162ace54bf62553acae767

### Get non-existent note with non-compliant mongo ID format, ID:invalidid
# 400: "error": "malformatted id"
GET http://localhost:3001/api/notes/invalidid

### Request to non-existent endpoint
# 404: "error": "unknown endpoint"
GET http://localhost:3001/api/thisendpointdoesnotexist

### Create new note without body.content
# 400: name missing/number missing
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "important": true
}

### Create new note with provided body content with default type (false)
# 200: JSON of created note with {content=content, important=False, id}
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "This note is posted to the database from Intellij IDEA HTTP Client tool at {{$isoTimestamp}}"
}

### Update note to toggle importance to true/false for ID: 651680bbdf6e808debaef7fa
# 200: JSON of updated note with {content, important, id}
PUT http://localhost:3001/api/notes/651680bbdf6e808debaef7fa
Content-Type: application/json

{
  "important": true
}

### Delete existing/non-existing note with non-compliant mongo ID:4017573324
# 400: "error": "malformatted id"
DELETE http://localhost:3001/api/notes/4017573324

### Delete existing/non-existing note compliant mongo ID:6516e4bced644246339419f0
# 204
DELETE http://localhost:3001/api/notes/6516e4bced644246339419f0
